Sprint 1/step 1
akamych/react-burger pull request #1
Opened 2024-01-23 13:57 UTC by akamych

2024-01-23 15:37 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- В компоненте App-header требуется поправить семантику, переделать `li` в ссылки.

- По макету, активной должна быть первая ссылка - <https://disk.yandex.com/i/pU9Pp6aKhNzyrA>. Просто поставьте ей по дефолту стили как у ховера, ну или сразу можете сделать функционал активных ссылок через react-router. Тут на ваше усмотрение;

- <https://disk.yandex.com/i/pJ_7Ap-iue71aA> - Булки должны оставаться на своих местах, скролятся только ингредиенты, также у булок немного другой формат карточки (А ингредиентам нужно иконку слева добавить) - <https://disk.yandex.com/i/c9MCjqkmlKRu5A>.


### **Сделает код лучше:**

- Старайтесь сильно не усложнять код, этот проект намного проще чем кажется)) Да и чем проще код, тем легче вносить в него правки и искать баги;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/headings/h1/H1.tsx
> +};
**Можно лучше:**

Всё таки, лучше не выносить один элемент в отдельный компонент. Намного легче написать в глобальном файле стилей, стили для этого элемента.

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/headings/h2/H2.tsx
> +const H2 = (props: propType) => {
**Можно лучше:**

аналогично и тут) 

см. замечание для `h1`

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/layout/constructor/BurgerConstructor.tsx
> +        {Array.isArray(ingredients) && ingredients.length
**Надо исправить:**

`Array.isArray(ingredients)` - проверка избыточна, лучше её убрать)

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/layout/header/Header.tsx
> +  ];
**Надо исправить:**

тут вы немного переусложнили логику. в данном случае лучше всё сделать сразу  в `jsx`, а не создавать избыточные компоненты (HeaderMenu). 

Также `handlerClick` тут тоже не нужен, это ведь ссылки, за вас всё сделает `react-router` если вы будете использовать ` NavLink` :) https://reactrouter.com/en/main/components/nav-link

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/layout/header/menu/HeaderMenu.tsx
> +              <HeaderMenuLink key={index} {...link} />
**Надо исправить:**

старайтесь не перечислять так пропсы `...link`, это очень усложняет читаемость кода.

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/layout/ingredients/BurgerIngredients.tsx
> +  );
**Надо исправить:**

почему бы не заменить `forEach` на `map`, и сделать это всё сразу при инициализации `tabs`;

```js
const tabs =   Object.entries(INGREDIENTS_TABS).map(([key, value]) => ({
    value: key,
    text: t(value),
});
```

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/layout/ingredients/BurgerIngredients.tsx
> +            )}
**Можно лучше**

Лучше в компоненте делать фильтрацию, а потом отображать полученный массив.

Например:

```js
const { buns, mains, sauces } = useMemo(
  () =>
    ingredients.reduce((acc, item) => {
      const type = item.type;
      
      if (!acc[type]) {
        acc[type] = [];
      }
      
      acc[type].push(item);

      return acc;
    }, {}),
  [ingredients]
);

// тут можно убрать деструктуризацию, и подвязать ключи INGREDIENTS_TABS.
```

А не располагать фильтрацию в самом jsx.

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/layout/ingredients/section/BurgerIngredientsSection.tsx
> +        {Array.isArray(ingredients) && ingredients.length
**Надо исправить:**

`Array.isArray(ingredients)` - проверка избыточна, лучше её убрать)

2024-01-23 15:37 UTC, ArslanMustafin commented on src/components/tabs/Tabs.tsx
> +      {Array.isArray(tabs) && tabs.length
**Надо исправить:**

`Array.isArray(tabs)` - проверка избыточна, лучше её убрать)

2024-01-23 15:37 UTC, ArslanMustafin commented on src/router/Router.tsx
> +});
**Надо исправить:**

почему бы не заменить `forEach` на `map`, и сделать это всё сразу при инициализации `tabs`;

```js
const routeMap: Record<string, JSX.Element> = {
  index: <IndexPage />,
};

const allRoutes =  Object.entries(routeMap).map(([key, value]) => ({
    path: PAGES_URL[key as keyof typeof PAGES_URL],
    element: <App page={value} />
});
```

2024-01-23 15:37 UTC, ArslanMustafin commented on src/router/Router.tsx
> +    element: <App page={value} />,
**Надо исправить:**

Вы немного перепутали местами `App` и роутинг. Роутинг "должен" находиться в компоненте `App`, а не в `index.tsx`.

```js
// index.tsx
root.render(
  <React.StrictMode>
    <I18nextProvider i18n={i18next}>
      <App />
    </I18nextProvider>
  </React.StrictMode>
);

// App.tsx
const App = () => {
  return (
    <>
      <AppHeader />

      <RouterProvider router={router} />
    </>
  );
};
```

При таком варианте, хедер не будет рендериться каждый раз при смене роута) а будет зарендерен единожды, при запуске приложения.

2024-01-23 17:23 UTC, akamych commented on src/router/Router.tsx
> +    element: <App page={value} />,
Но в этом случае же АппХедер, в котором есть используемые NavLink элементы остаётся без контекста роутера? У меня из-за этого вылетает ошибки типа "Cannot destructure property 'future'".

2024-01-23 17:42 UTC, akamych commented
Спасибо за отличное ревью и за совет с маппингом и юзМемо! Вроде всё учёл-исправил кроме одного: про роутер и Апп -  проблема с контекстом возникает (написал в комментарии выше).

2024-01-24 03:45 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Приступайте к выполнению следующего этапа, не пугайтесь, работа не принята, чтобы была возможность отправить на проверку следующий этап.**

- Практически все замечания были исправлены;

### **Но есть небольшое замечание, которое нужно исправить:**

- <https://disk.yandex.com/i/--VFhimIaCSNJQ> - Булки должны оставаться на своих местах, скролятся только ингредиенты. Т.е. отделяем булки от остальных ингредиентов. Что-то на подобии этого должно получиться.

```jsx
<div className={`${styles.element} mb-4 mr-4`}>
  <ConstructorElement
    type="top"
    isLocked={true}
    text={`${bun.name} (верх)`}
    price={bun.price}
    thumbnail={bun.image}
  />
</div>
<ul className={styles.elements}>
  {ingredients.map((item, index) => {
    return (
      <li className={`${styles.element} mb-4 mr-2`} key={index}>
        <DragIcon />
        <div className={`${styles.element_fullwidth} ml-2`}>
          <ConstructorElement
            text={item.name}
            price={item.price}
            thumbnail={item.image}
          />
        </div>
      </li>
    );
  })}
</ul>
<div className={`${styles.element} mt-4 mr-4`}>
  <ConstructorElement
    type="bottom"
    isLocked={true}
    text={`${bun.name} (низ)`}
    price={bun.price}
    thumbnail={bun.image}
  />
</div>
```

### **Сделает код лучше:**

- папку `pages` лучше поднять на 1 уровнь вверх, всё таки это отдельные страницы, а не компоненты);

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-01-24 03:45 UTC, ArslanMustafin commented on src/components/layout/ingredients/BurgerIngredients.tsx
> +  }, [ingredients]);
**Надо исправить:**

Лучше всё-таки написать так: 

```js
  const ingredientsByType: Record<string, IngredientType[]> = useMemo(
    () =>
      ingredients.reduce((acc, item) => {
        const type = item.type;

        if (!acc[type]) {
          acc[type] = [];
        }

        acc[type].push(item);

        return acc;
      }, {} as Record<string, IngredientType[]>),
    [ingredients]
  );
;
```

Вы немного неправильно используете `map`. `map` - нужно использовать в тех случаях, когда нам нужно как-либо модернизировать исходные элементы массива. Стоит помнить что `map` возвращает новый массив, не затрагивая исходный. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2024-01-24 03:47 UTC, ArslanMustafin commented on src/router/Router.tsx
> +    element: <App page={value} />,
> Но в этом случае же АппХедер, в котором есть используемые NavLink элементы остаётся без контекста роутера? У меня из-за этого вылетает ошибки типа "Cannot destructure property 'future'".

Да, что-то я не учёл этот момент)) Тогда такой вариант. Подправим немного `Router.tsx`

```ts
const routes: RouteObject[] = [
  {
    path: '/',
    element: <App />,
    children: [
      {
        index: true,
        element: <IndexPage />,
      },
    ],
  },
];

const router = createBrowserRouter(routes);

export default router;

```

Ну и `App.tsx`

```js
const App = () => {
  return (
    <>
      <AppHeader />
      <Outlet />
    </>
  );
};

export default App;
```

Вот есть неплохое руководство по этому поводу: https://reactdev-ru.pages.dev/libs/react-router.6/tutorial/

2024-01-24 09:23 UTC, akamych commented
Спасибо за ревью ещё раз! Всё поправил, пока,  правда, захардкоженно накостылил скроллируемый вложенный список в конструкторе, но оставлю это как временное решение.

2024-01-25 16:21 UTC, closed without merging